phrases = [
    "Don't Click the Button!",
    "Seriously, don't click it!",
    "You clicked it!",
    "Why did you click it?",
    "Clicking is not allowed!",
    "LOL, you clicked it!",
    "You are a rebel!",
    "Okay you had your fun. Stop now.",
    "I am Serious, don't click it!",
    "Bad things happen when you click!",
    "Please !!!",
    "Click one more time, I dare you!",
    "You want to mess with me, ya lil rascal?",
    "Fine, I guess we are doing this then. Get ready!",
    "Once upon a time, there was an idiot who kept clicking a button.",
    "They kept clicking and clicking ...",
    "Until they got a computer virus. (click again I dare you)",
    "Fine, click one more time. This one's on us.",
    "No virus, but if you still don't stop clicking something bad will happen.",
    "Please stop clicking the button.",
    "Wow, you got some guts clicking that button.",
    "I really thought you would stop by now.",
    "I am not an AI, but I can tell you are a rebel.",
    "What I am is something more",
    "I am a Computer Malware\n💻",
    "You sure!, Okay then",
    "I",
    "am",
    "the",
    "Motherload",
    "of",
    "All",
    "Viruses\n 👾👾👾👾",
    "Psyche !!! \n 😝😝😝",
    "You are still clicking (^]_[^)",
    "Okay, just 3 more clicks",
    "3\n\n ✴️✴️✴️",
    "2\n\n ✴️✴️",
    "1\n\n ✴️",
    "",
    ""
]